# -*- coding: utf-8 -*-
"""SVM_indiv_CT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L2rTZ0bzHSR4ZcdkIRERImcgCDTl9ZoZ
"""

#Load the required libraries
import os
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.utils import resample
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import GridSearchCV, StratifiedKFold
from sklearn.decomposition import PCA
import matplotlib.colors as colors
import matplotlib.pyplot as plt
!pip3 install xlrd
from sklearn.datasets import fetch_california_housing
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.metrics import ConfusionMatrixDisplay
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.preprocessing import scale
from google.colab import drive
from sklearn.preprocessing import StandardScaler
drive.mount('/content/drive')

# Import the data set
data = pd.read_csv('/content/drive/MyDrive/Machine Learning/normalized_data_resampling.csv')
print(data)
print(data.shape)

df_labels = data.iloc[:,-1]
df_labels = df_labels.to_numpy()
np.savetxt('all_labels.csv', df_labels, delimiter=",")
print(df_labels.shape)
print(df_labels)
# print how many 1 we have in labels
print(np.sum(df_labels))

# import feature data
data2 = pd.read_csv('/content/drive/MyDrive/Machine Learning/NN-inputs-ants-resampling.csv')
df_trials = data2.iloc[:,1:]
print(df_trials.shape)
print(df_trials.head())
df_trials.to_numpy()
# write to a csv file
np.savetxt('all_trials.csv', df_trials, delimiter=",")

print(df_labels.min())
print(df_labels.max())

# put all features in a list
all_features = df_trials.columns.tolist()
print(len(all_features))
print(all_features)
print(type(all_features))
print(type(df_trials))

"""## Start Support Vector Machine (SVM)"""

from sklearn.preprocessing import scale
# split the data into train and test
test_ratio = 0.15
X = pd.read_csv("./all_trials.csv", header=0)
y = pd.read_csv("./all_labels.csv", header=0)

train_x, test_x, train_y, test_y = train_test_split(X,y,random_state=42,test_size=test_ratio)
train_x = scale(train_x)
test_x = scale(test_x)

# create the SVM classifier
clf_svm = SVC(random_state = 42)
clf_svm.fit(train_x, train_y)
clf_svm.score(train_x, train_y) # to evaluate the accuracy of the trained model on the training dataset
# predict the labels
y_pred = clf_svm.predict(test_x)
accuracy = accuracy_score(test_y, y_pred)
print("Accuracy:", accuracy)

class_names = ['good performance', 'poor performance']
disp = ConfusionMatrixDisplay.from_estimator(clf_svm, test_x, test_y, display_labels=class_names, cmap=plt.cm.Blues)
disp.ax_.set_title("Confusion Matrix")
print(disp)

print(train_x.shape[1])
print(classification_report(test_y, y_pred))

"""##  Do Trimming Round"""

def get_indices_from_file (file_path, cutoff):
  data = np.load(file_path)
  indices_bool = (data >= cutoff)
  indices_bool = np.invert(indices_bool)
  indices = np.where(indices_bool)[0]
  return indices

#target_num_ROIs = int(2/3*num_ROIs)
#num_ROIs = x_tensor.shape[1]

def find_optimal_cutoffs(file_path):
  accuracy_data = np.load(file_path)
  cutoff = 1
  step = 0.005
  num_features = len(accuracy_data)
  target_num_features = int(2/3*num_features)

  while num_features > target_num_features:
    cutoff -= step
    num_features = len(get_indices_from_file(file_path, cutoff))

  #check if previous cutoff was closer to the target
  prev_num_features = len(get_indices_from_file(file_path, cutoff+step))
  if abs(prev_num_features - target_num_features) < abs(num_features - target_num_features):
    cutoff += step

  return cutoff


save_dir = f"./SVM_indiv_features_CA"
os.makedirs(save_dir, exist_ok=True)
test_ratio = 0.15
num_rounds = 6 # 9
num_splits = 100 # 800
X = pd.read_csv("./all_trials.csv", header=0)
y = pd.read_csv("./all_labels.csv", header=0)

train_x, test_x, train_y, test_y = train_test_split(X,y,random_state=42,test_size=test_ratio)
#train_x = scale(train_x)
#test_x = scale(test_x)
scaler = StandardScaler()
train_x = scaler.fit_transform(train_x)  # Fit on training data
test_x = scaler.transform(test_x)  # Transform test data using the same scaling
bs = 32

accuracies = []
print("\n--Training data samples--", train_x.shape, test_x.shape)
print("\n--Testing data samples--", train_y.shape, test_y.shape)

# create the SVM classifier
#clf_svm = SVC(random_state = 42)

for k in range(num_rounds):
  print(f'\n\nround: {k}')
  new_train_x = train_x
  new_test_x = test_x
  features = np.array(all_features.copy())
  print(features)
  param_grid = {
        'C': [0.01, 0.1, 0.5, 1, 10, 100, 1000, 5000, 10000],  # Expanded C values
        'gamma': [1, 0.1, 0.01, 0.001, 0.0001, 1e-5, 1e-6],  # Expanded gamma values
        'kernel': ['rbf']
               }

  optimal_params = GridSearchCV(SVC(), param_grid, cv=5, scoring='accuracy', verbose=0)
  optimal_params.fit(new_train_x, train_y.values.ravel())

  # Print the best parameters
  # print("Best parameters:", optimal_params.best_params_)

  # Create and train the SVM classifier with best parameters
  clf_svm = SVC(random_state=42, **optimal_params.best_params_)

  # we want to do this unless it's the first time:
  # load the ith accuracy file, get its indices via cutoff function, then apply
  for l in range(k): # this for loop is for trim trim trim!!!
    file_path = f'./SVM_indiv_features_CA/SVM_Mean_{l+1}_california_acc.npy'
    cutoff = find_optimal_cutoffs(file_path)
    indices = get_indices_from_file(file_path, cutoff)
    print("n\n\nIndices", indices)
    new_train_x = train_x[:, indices]
    new_test_x = test_x[:, indices]
    scaler = StandardScaler()
    new_train_x = scaler.fit_transform(new_train_x)  # Fit on training data
    new_test_x = scaler.transform(new_test_x)  # Transform test data using the same scaling
    features = features[indices]
    #print("\n\nremained features" ,features)

  num_features = new_train_x.shape[1]
  print(f"num_features: {num_features}")
  print("features", features)
  accuracies = []
  for i in range(num_features):
    feature_indices = [j for j in range(num_features) if j!=i]
    # select a subset of features with highest accuracies
    x_subset = new_train_x[:, feature_indices]
    xtest_subset = new_test_x[:, feature_indices]
    # add a for loop with split in  for cross validation
    split_accuracies = []
    for split in range(num_splits):
      og_num_data_pts = x_subset.shape[0]
      #print("x subset SHAPE", x_subset.shape)
      #print("y train SHAPE", train_y.shape)
      combined_x = np.concatenate((x_subset, xtest_subset), axis=0)#this basically shuffles train and test
      #print("Combined x shape", combined_x.shape)
      combined_y = np.concatenate((train_y.values.ravel(), test_y.values.ravel()), axis=0)
      #print("Combined y shape", combined_y.shape)
      num_data_pts = combined_x.shape[0]
      # choose a new split
      train_x_indices  = np.random.choice(num_data_pts, size=og_num_data_pts, replace=False)
      inverted_indices = [i for i in range(num_data_pts) if i not in train_x_indices]
      train_x_split = combined_x[train_x_indices]
      _y_train = combined_y[train_x_indices]
      # god forgive me
      test_x_split = combined_x[inverted_indices]
      _y_test = combined_y[inverted_indices]
      #train_x_split = scale(train_x_split)
      #test_x_split = scale(test_x_split) # do i need this??
      clf_svm.fit(train_x_split, _y_train.ravel())
      clf_svm.score(train_x_split, _y_train.ravel()) # to evaluate the accuracy of the trained model on the training dataset
      # predict the labels
      y_pred = clf_svm.predict(test_x_split)
      accuracy = accuracy_score(_y_test, y_pred)
      #print("Accuracy:", accuracy)
      split_accuracies.append(accuracy)


    accuracies.append(np.array(split_accuracies))
    print("AVG VAL ACCURACY", np.mean(split_accuracies))

  # draw confusion matrix for each round
  class_names = ['good performance', 'poor performance']
  clf_svm = SVC(random_state = 42, **optimal_params.best_params_)
  clf_svm.fit(new_train_x, train_y.values.ravel())
  disp = ConfusionMatrixDisplay.from_estimator(clf_svm, new_test_x, test_y, display_labels=class_names, cmap=plt.cm.Blues)
  disp.ax_.set_title("Confusion Matrix")
  plt.show()
  # report precision
  y_pred = clf_svm.predict(new_test_x)
  print(classification_report(test_y, y_pred))

  # save the accuracies
  save_file = f'./SVM_indiv_features_CA/SVM_{k+1}_california_acc.npy'
  np.save(save_file, accuracies)

  save_file_mean = f'./SVM_indiv_features_CA/SVM_Mean_{k+1}_california_acc.npy'
  np.save(save_file_mean, np.mean(accuracies, axis=1))
