# -*- coding: utf-8 -*-
"""SVM_indiv_CT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L2rTZ0bzHSR4ZcdkIRERImcgCDTl9ZoZ
"""

#Load the required libraries
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.utils import resample
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import GridSearchCV, StratifiedKFold
from sklearn.decomposition import PCA
import matplotlib.colors as colors
import matplotlib.pyplot as plt
!pip3 install xlrd
from sklearn.datasets import fetch_california_housing
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.metrics import ConfusionMatrixDisplay
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.preprocessing import scale
from google.colab import drive
from sklearn.preprocessing import StandardScaler
drive.mount('/content/drive')

# Import the data set
data = pd.read_csv('/content/drive/MyDrive/Machine Learning/normalized_data_resampling.csv')
print(data)
print(data.shape)

df_labels = data.iloc[:,-1]
df_labels = df_labels.to_numpy()
np.savetxt('all_labels.csv', df_labels, delimiter=",")
print(df_labels.shape)
print(df_labels)
# print how many 1 we have in labels
print(np.sum(df_labels))

# import feature data
data2 = pd.read_csv('/content/drive/MyDrive/Machine Learning/NN-inputs-ants-resampling.csv')
df_trials = data2.iloc[:,1:]
print(df_trials.shape)
print(df_trials.head())
df_trials.to_numpy()
# write to a csv file
np.savetxt('all_trials.csv', df_trials, delimiter=",")

print(df_labels.min())
print(df_labels.max())

# put all features in a list
all_features = df_trials.columns.tolist()
print(len(all_features))
print(all_features)
print(type(all_features))
print(type(df_trials))

"""## Start Support Vector Machine (SVM)"""

from sklearn.preprocessing import scale
# split the data into train and test
test_ratio = 0.15
X = pd.read_csv("./all_trials.csv", header=0)
y = pd.read_csv("./all_labels.csv", header=0)

print(X.shape)
print(y.shape)

train_x, test_x, train_y, test_y = train_test_split(X,y,random_state=42,test_size=test_ratio)
train_x = scale(train_x)
test_x = scale(test_x)

# create the SVM classifier
clf_svm = SVC(random_state = 42)
clf_svm.fit(train_x, train_y)
clf_svm.score(train_x, train_y) # to evaluate the accuracy of the trained model on the training dataset
# predict the labels
y_pred = clf_svm.predict(test_x)
accuracy = accuracy_score(test_y, y_pred)
print("Accuracy:", accuracy)

class_names = ['good performance', 'poor performance']
disp = ConfusionMatrixDisplay.from_estimator(clf_svm, test_x, test_y, display_labels=class_names, cmap=plt.cm.Blues)
disp.ax_.set_title("Confusion Matrix")
print(disp)

print(train_x.shape[1])
print(classification_report(test_y, y_pred))

"""##  Do Trimming Round"""

def get_indices_from_file (file_path, cutoff):
  data = np.load(file_path)
  indices_bool = (data >= cutoff)
  indices_bool = np.invert(indices_bool)
  indices = np.where(indices_bool)[0]
  return indices

#target_num_ROIs = int(2/3*num_ROIs)
#num_ROIs = x_tensor.shape[1]

def find_optimal_cutoffs(file_path):
  accuracy_data = np.load(file_path)
  cutoff = 1
  step = 0.005
  num_features = len(accuracy_data)
  target_num_features = int(2/3*num_features)

  while num_features > target_num_features:
    cutoff -= step
    num_features = len(get_indices_from_file(file_path, cutoff))

  #check if previous cutoff was closer to the target
  prev_num_features = len(get_indices_from_file(file_path, cutoff+step))
  if abs(prev_num_features - target_num_features) < abs(num_features - target_num_features):
    cutoff += step

  return cutoff

import os

save_dir = f"./SVM_indiv_features_CA"
os.makedirs(save_dir, exist_ok=True)
test_ratio = 0.15
num_rounds = 6 # 9
num_splits = 100 # 800
X = pd.read_csv("./all_trials.csv", header=0)
y = pd.read_csv("./all_labels.csv", header=0)
print(X.shape)
print(y.shape)
train_x, test_x, train_y, test_y = train_test_split(X,y,random_state=42,test_size=test_ratio)
#train_x = scale(train_x)
#test_x = scale(test_x)
scaler = StandardScaler()
train_x = scaler.fit_transform(train_x)  # Fit on training data
test_x = scaler.transform(test_x)  # Transform test data using the same scaling
bs = 32

accuracies = []
print("\n--Training data samples--", train_x.shape, test_x.shape)
print("\n--Testing data samples--", train_y.shape, test_y.shape)

# create the SVM classifier
#clf_svm = SVC(random_state = 42)

for k in range(num_rounds):
  print(f'\n\nround: {k}')
  new_train_x = train_x
  new_test_x = test_x
  features = np.array(all_features.copy())
  print(features)
  param_grid = {
        'C': [0.01, 0.1, 0.5, 1, 10, 100, 1000, 5000, 10000],  # Expanded C values
        'gamma': [1, 0.1, 0.01, 0.001, 0.0001, 1e-5, 1e-6],  # Expanded gamma values
        'kernel': ['rbf']
               }

  optimal_params = GridSearchCV(SVC(), param_grid, cv=5, scoring='accuracy', verbose=0)
  optimal_params.fit(new_train_x, train_y.values.ravel())

  # Print the best parameters
  # print("Best parameters:", optimal_params.best_params_)

  # Create and train the SVM classifier with best parameters
  clf_svm = SVC(random_state=42, **optimal_params.best_params_)

  # we want to do this unless it's the first time:
  # load the ith accuracy file, get its indices via cutoff function, then apply
  for l in range(k): # this for loop is for trim trim trim!!!
    file_path = f'./SVM_indiv_features_CA/SVM_Mean_{l+1}_california_acc.npy'
    cutoff = find_optimal_cutoffs(file_path)
    indices = get_indices_from_file(file_path, cutoff)
    print("n\n\nIndices", indices)
    new_train_x = train_x[:, indices]
    new_test_x = test_x[:, indices]
    scaler = StandardScaler()
    new_train_x = scaler.fit_transform(new_train_x)  # Fit on training data
    new_test_x = scaler.transform(new_test_x)  # Transform test data using the same scaling
    features = features[indices]
    #print("\n\nremained features" ,features)

  num_features = new_train_x.shape[1]
  print(f"num_features: {num_features}")
  print("features", features)
  accuracies = []
  for i in range(num_features):
    feature_indices = [j for j in range(num_features) if j!=i]
    # select a subset of features with highest accuracies
    x_subset = new_train_x[:, feature_indices]
    xtest_subset = new_test_x[:, feature_indices]
    # add a for loop with split in  for cross validation
    split_accuracies = []
    for split in range(num_splits):
      og_num_data_pts = x_subset.shape[0]
      #print("x subset SHAPE", x_subset.shape)
      #print("y train SHAPE", train_y.shape)
      combined_x = np.concatenate((x_subset, xtest_subset), axis=0)#this basically shuffles train and test
      #print("Combined x shape", combined_x.shape)
      combined_y = np.concatenate((train_y.values.ravel(), test_y.values.ravel()), axis=0)
      #print("Combined y shape", combined_y.shape)
      num_data_pts = combined_x.shape[0]
      # choose a new split
      train_x_indices  = np.random.choice(num_data_pts, size=og_num_data_pts, replace=False)
      inverted_indices = [i for i in range(num_data_pts) if i not in train_x_indices]
      train_x_split = combined_x[train_x_indices]
      _y_train = combined_y[train_x_indices]
      # god forgive me
      test_x_split = combined_x[inverted_indices]
      _y_test = combined_y[inverted_indices]
      #train_x_split = scale(train_x_split)
      #test_x_split = scale(test_x_split) # do i need this??
      clf_svm.fit(train_x_split, _y_train.ravel())
      clf_svm.score(train_x_split, _y_train.ravel()) # to evaluate the accuracy of the trained model on the training dataset
      # predict the labels
      y_pred = clf_svm.predict(test_x_split)
      accuracy = accuracy_score(_y_test, y_pred)
      #print("Accuracy:", accuracy)
      split_accuracies.append(accuracy)


    accuracies.append(np.array(split_accuracies))
    print("AVG VAL ACCURACY", np.mean(split_accuracies))

  # draw confusion matrix for each round
  class_names = ['good performance', 'poor performance']
  clf_svm = SVC(random_state = 42, **optimal_params.best_params_)
  clf_svm.fit(new_train_x, train_y.values.ravel())
  disp = ConfusionMatrixDisplay.from_estimator(clf_svm, new_test_x, test_y, display_labels=class_names, cmap=plt.cm.Blues)
  disp.ax_.set_title("Confusion Matrix")
  plt.show()
  # report precision
  y_pred = clf_svm.predict(new_test_x)
  print(classification_report(test_y, y_pred))

  # save the accuracies
  save_file = f'./SVM_indiv_features_CA/SVM_{k+1}_california_acc.npy'
  np.save(save_file, accuracies)

  save_file_mean = f'./SVM_indiv_features_CA/SVM_Mean_{k+1}_california_acc.npy'
  np.save(save_file_mean, np.mean(accuracies, axis=1))

print(train_x.shape[1])
print(classification_report(test_y, y_pred))

import matplotlib.pyplot as plt
import numpy as np
data = np.load('./SVM_indiv_features_CA/SVM_Mean_4_california_acc.npy')
print(data)
plt.hist(data)
# put x and y labels
plt.xlabel('Accuracy')
plt.ylabel('Frequency')
plt.title('Histogram of Accuracy')
plt.show()

# improve the model using hyperparameters
param_grid = {'C':[0.5,0.1,1,10,100,1000],
              'gamma':['scale', 1,0.1, 0.01,0.001,0.0001],
              'kernel':['rbf']}

optimal_params = GridSearchCV(SVC(), param_grid, cv = 5, scoring='accuracy', verbose=3)
optimal_params.fit(train_x, train_y)

# see "best" parameters
print("best params", optimal_params.best_params_)
print("best scores", optimal_params.best_score_)

# refit model with optimal hyperparameters
grid_predictions = optimal_params.predict(test_x)
clf_svm = SVC(random_state = 42, C=1000, gamma=0.01)
clf_svm.fit(train_x, train_y)

#calculate overall accuracy
y_pred = clf_svm.predict(test_x)
accuracy = accuracy_score(test_y, y_pred)
print(f'Accuracy: {accuracy:.2%}')

# plot confusion matrix
class_names = ['Cheap', 'Expensive']
disp = ConfusionMatrixDisplay.from_estimator(
        clf_svm,
        test_x,
        test_y,
        display_labels=class_names,
        cmap=plt.cm.Blues)

# do dimensionality reduction - just for visualization
pca = PCA()
train_x_pca = pca.fit_transform(train_x)
print("train_x_pca_shape",train_x_pca.shape)
print(train_x_pca[:10])
print(train_x_pca[:,2])
per_var = np.round(pca.explained_variance_ratio_*100, decimals=1)
#plot scree plot
plt.bar(x=range(1, len(per_var)+1), height=per_var)
plt.ylabel("Explained variance (%)")
plt.xlabel('Principal Components')
plt.title('Scree Plot')
plt.xticks(range(1, len(per_var) + 1))
plt.show()

train_pc1_coords = train_x_pca[:, 0] #first component
train_pc2_coords = train_x_pca[:, 1] #second component

pca_train_scaled = scale(np.column_stack((train_pc1_coords, train_pc2_coords)))
print(pca_train_scaled)
param_grid = {'C':[0.01, 0.1, 0.5, 1, 10, 100],
              'gamma':[1, 0.75, 0.5, 0.25, 0.1, 0.01, 0.001],
              'kernel':['rbf']}
optimal_params = GridSearchCV(SVC(), param_grid, cv = 5, scoring='accuracy', verbose=3)

optimal_params.fit(pca_train_scaled, train_y)
print("best params", optimal_params.best_params_)
print("best scores", optimal_params.best_score_)

clf_svm = SVC(random_state=42, C=100, gamma=1)
clf_svm.fit(pca_train_scaled, train_y)

X_test_pca = pca.transform(train_x)
test_pc1_coords = X_test_pca[:, 0]
test_pc2_coords = X_test_pca[:, 1]

x_min = test_pc1_coords.min()-1
x_max = test_pc1_coords.max()+1
y_min = test_pc2_coords.min()-1
y_max = test_pc2_coords.max()+1

xx, yy = np.meshgrid(np.arange(start=x_min, stop=x_max, step=0.1),
                     np.arange(start=y_min, stop=y_max, step=0.1))


Z = clf_svm.predict(np.column_stack((xx.ravel(), yy.ravel())))
Z = Z.reshape(xx.shape)

# visualizing the data
fig, ax = plt.subplots(figsize=(10,10))
ax.contourf(xx,yy, Z, alpha=0.1)
cmap = colors.ListedColormap(['#e41a1c', '#4daf4a'])
#train_y = train_y.tolist() #if it is numpy
train_y=train_y.values.ravel()#if it is pandas df
scatter = ax.scatter(test_pc1_coords, test_pc2_coords, c=train_y, cmap=cmap, s=100, edgecolors='k', alpha=0.7)
legend = ax.legend(*scatter.legend_elements(), title="Price", loc="upper right")


legend.get_texts()[0].set_text('Cheap')
legend.get_texts()[1].set_text('Expensive')
ax.set_ylabel('PC2')
ax.set_xlabel('PC1')
ax.set_title('Visualizing the Decision Boundary Using Principal Components')
plt.show()

"""# for 100 datapoints"""

# Load all np files into a list
file_paths = [f"./100_SVM_features_CA/SVM_Mean_1_{i}_california_acc.npy" for i in range(10)]
accuracies = [np.load(file_path) for file_path in file_paths]
print(accuracies)
print(accuracies[0])

plt.plot(accuracies[0], label='Run 1')
plt.plot(accuracies[1], label='Run 2')
plt.plot(accuracies[2], label='Run 3')
plt.plot(accuracies[3], label='Run 4')
plt.plot(accuracies[4], label='Run 5')
plt.plot(accuracies[5], label='Run 6')
plt.plot(accuracies[6], label='Run 7')
plt.plot(accuracies[7], label='Run 8')
plt.plot(accuracies[8], label='Run 9')
plt.plot(accuracies[9], label='Run 10')
plt.xlabel('Model Number')
plt.ylabel('Accuracy')

plt.legend(loc='upper left', bbox_to_anchor=(1, 1))
plt.tight_layout()  # Adjust layout to make room for the legend
plt.show()

import itertools
from scipy.stats import kendalltau
correlation_results = []
for i,j in itertools.combinations(range(len(accuracies)), 2):
    kendall_corr, _ = kendalltau(accuracies[i],accuracies[j])
    correlation_results.append(kendall_corr)

print("Pairwise comparisons:", correlation_results)
average_kendall = np.mean(correlation_results)
print("Avg Kendall:",average_kendall)
print("Number of comparisons:",len(correlation_results))

"""# for 500 datapoints"""

file_paths = [f"./500_SVM_features_CA/SVM_Mean_1_{i}_california_acc.npy" for i in range(10)]
accuracies = [np.load(file_path) for file_path in file_paths]
print(accuracies)
print(accuracies[0])

plt.plot(accuracies[0], label='Run 1')
plt.plot(accuracies[1], label='Run 2')
plt.plot(accuracies[2], label='Run 3')
plt.plot(accuracies[3], label='Run 4')
plt.plot(accuracies[4], label='Run 5')
plt.plot(accuracies[5], label='Run 6')
plt.plot(accuracies[6], label='Run 7')
plt.plot(accuracies[7], label='Run 8')
plt.plot(accuracies[8], label='Run 9')
plt.plot(accuracies[9], label='Run 10')
plt.xlabel('Model Number')
plt.ylabel('Accuracy')

plt.legend(loc='upper left', bbox_to_anchor=(1, 1))
plt.tight_layout()  # Adjust layout to make room for the legend
plt.show()

import itertools
from scipy.stats import kendalltau
correlation_results = []
for i,j in itertools.combinations(range(len(accuracies)), 2):
    kendall_corr, _ = kendalltau(accuracies[i],accuracies[j])
    correlation_results.append(kendall_corr)

print("Pairwise comparisons:", correlation_results)
average_kendall = np.mean(correlation_results)
print("Avg Kendall:",average_kendall)
print("Number of comparisons:",len(correlation_results))

"""# for 1500 datapoints"""

file_paths = [f"./1500_SVM_features_CA/SVM_Mean_1_{i}_california_acc.npy" for i in range(10)]
accuracies = [np.load(file_path) for file_path in file_paths]
print(accuracies)
print(accuracies[0])

plt.plot(accuracies[0], label='Run 1')
plt.plot(accuracies[1], label='Run 2')
plt.plot(accuracies[2], label='Run 3')
plt.plot(accuracies[3], label='Run 4')
plt.plot(accuracies[4], label='Run 5')
plt.plot(accuracies[5], label='Run 6')
plt.plot(accuracies[6], label='Run 7')
plt.plot(accuracies[7], label='Run 8')
plt.plot(accuracies[8], label='Run 9')
plt.plot(accuracies[9], label='Run 10')
plt.xlabel('Model Number')
plt.ylabel('Accuracy')

plt.legend(loc='upper left', bbox_to_anchor=(1, 1))
plt.tight_layout()  # Adjust layout to make room for the legend
plt.show()

import itertools
from scipy.stats import kendalltau
correlation_results = []
for i,j in itertools.combinations(range(len(accuracies)), 2):
    kendall_corr, _ = kendalltau(accuracies[i],accuracies[j])
    correlation_results.append(kendall_corr)

print("Pairwise comparisons:", correlation_results)
average_kendall = np.mean(correlation_results)
print("Avg Kendall:",average_kendall)
print("Number of comparisons:",len(correlation_results))

"""# for 2000 datapoints"""

file_paths = [f"./2000_SVM_features_CA/SVM_Mean_1_{i}_california_acc.npy" for i in range(10)]
accuracies = [np.load(file_path) for file_path in file_paths]
print(accuracies)
print(accuracies[0])

plt.plot(accuracies[0], label='Run 1')
plt.plot(accuracies[1], label='Run 2')
plt.plot(accuracies[2], label='Run 3')
plt.plot(accuracies[3], label='Run 4')
plt.plot(accuracies[4], label='Run 5')
plt.plot(accuracies[5], label='Run 6')
plt.plot(accuracies[6], label='Run 7')
plt.plot(accuracies[7], label='Run 8')
plt.plot(accuracies[8], label='Run 9')
plt.plot(accuracies[9], label='Run 10')
plt.xlabel('Model Number')
plt.ylabel('Accuracy')

plt.legend(loc='upper left', bbox_to_anchor=(1, 1))
plt.tight_layout()  # Adjust layout to make room for the legend
plt.show()

import itertools
from scipy.stats import kendalltau
correlation_results = []
for i,j in itertools.combinations(range(len(accuracies)), 2):
    kendall_corr, _ = kendalltau(accuracies[i],accuracies[j])
    correlation_results.append(kendall_corr)

print("Pairwise comparisons:", correlation_results)
average_kendall = np.mean(correlation_results)
print("Avg Kendall:",average_kendall)
print("Number of comparisons:",len(correlation_results))

example1 = [.6, .7, .5, .8, .9, .55, .85, .8]
example2 = [.6, .7, .5, .8, .9, .55, .85, .8]
kendall_corr, _ = kendalltau(example1,example2)
print("kendall_corr:", kendall_corr)

example1 = [.6, .7, .5, .8, .9, .55, .85, .8]
example2 = [.6, .7, .55, .8, .9, .5, .85, .8]
kendall_corr, _ = kendalltau(example1,example2)
print("kendall_corr:", kendall_corr)

example1 = [.6, .7, .5, .8, .9, .55, .85, .8]
example2 = [.6, .5, .7, .8, .9, .55, .85, .8]
kendall_corr, _ = kendalltau(example1,example2)
print("kendall_corr:", kendall_corr)

example1 = [.6, .7, .5, .8, .9, .55, .85, .8]
example2 = [.6, .5, .7, .9, .8, .55, .85, .8]
kendall_corr, _ = kendalltau(example1,example2)
print("kendall_corr:", kendall_corr)